!-------------------------------------------------------------------------!
Module Software_Info_Mod
!-------------------------------------------------------------------------!


  ! --------------------------------------------------------
  ! --- This module is used to give some common info about
  !     the software that it is part off......
  !
  !     Ingve Simonsen, Paris Mar 2007
  !
  ! --------------------------------------------------------




  ! ---------------------------
  ! --- The use statement
  ! ---------------------------

  
  ! --------------------------------------
  ! --- The Publicly avaiable quantities
  ! --------------------------------------
  Public :: Software_Info_Type
  Public :: Software_Info_Set
  Public :: Software_Info_String
  !Public :: current_date_time_string
  
  ! --------------------------------------
  ! --- Everyting is Private by default
  ! --------------------------------------
  Private


  ! --------------------------------------------
  ! --- Define default parameter settings
  ! --------------------------------------------

  Integer, parameter :: STR_LEN      = 150
  Integer, parameter :: STR_DATE_LEN = 21

  !
  Type Software_Info_Type
     Character(len=STR_LEN)      ::  Name         ! Software name
     Character(len=STR_LEN)      ::  Author(2)    ! Software author
     Character(len=STR_LEN)      ::  Email(2)     ! Software author email
     Character(len=STR_LEN)      ::  CopyRight    
     Character(len=STR_LEN)      ::  Version      ! Software Version  
     Character(len=STR_LEN)      ::  Revision     ! Software Revision
     Character(len=STR_LEN)      ::  FromYear     ! Start year for the code....  
     Character(len=11)           ::  Compile_Date ! Date of this compiled version
     Character(len=8)            ::  Compile_Time ! Time of this compiled version
  End Type Software_Info_Type


  !
  ! ------------------------
  !
  
Contains


  !----------------------------------------!
  Subroutine Software_Info_Set( Info, Name )
  !----------------------------------------!
    !
    ! Set some information about the software
    !
    Use compile_date_time_m, only : get_compile_date, get_compile_time
    Implicit None
    Type(Software_Info_Type), intent(inout)               :: Info
    Character(len=*),         intent(in),   optional      :: Name
    ! Local
    Integer :: ipos
    Character(len=100) :: Software_Name
    Character(len=200) :: string

    ! Set the name of the Software.....
    if (present(Name) ) then
       Info%Name       = Trim(Adjustl(Name))
    else
       call getarg(0, Software_Name )  
       Info%Name       = Trim(adjustl( Software_Name ))  
    end if

   
    Info%Version      =  "2.0"
    Info%Author(1)    =  "Ingve Simonsen"
    Info%Email(1)     =  "<Ingve.Simonsen@ntnu.no>"
    Info%Author(2)    =  "Remi Lazzari"
    Info%Email(2)     =  "<Remi.Lazzari@insp.jussieu.fr>"
    Info%FromYear     =  "2008"
    Info%Revision     =  Get_Repos_Revision_Number()
    Info%Copyright    =  Trim(Adjustl(Copyright_String( Info ) ))
    Info%Compile_Date =  get_compile_date()
    Info%Compile_Time =  get_compile_time()
    

  contains
    

    Function Get_Repos_Revision_Number() result(res)
      ! This routine gets the SVN Revison number 
      ! from the file VERSION (if it exists)
      Implicit None
      character(len=25) :: res
      ! Local
      character(len=100):: rcs_id
      
      ! This file is automatically generated by the made file 
      Include ".rcs_id"

      res  = trim(adjustl(rcs_id))

      !Integer    :: istart, iend
      !character(len=*),parameter :: REV="$Rev: 59 $"
      !character(len=*),parameter :: tag="$Rev:"
  
      !istart = Index( REV, tag) + len(tag)
      !iend   = Index( REV(istart+1:), " " ) + istart
      !res = REV(istart:iend)
      
    End Function Get_Repos_Revision_Number
    !
    !
    Function  Copyright_String(Info) Result( string )
      !
      ! Returns a Copyright string about the software...
      !
      Use SFL_Util, Only : SFL_YearString
      Implicit None
      Type(Software_Info_Type), intent(in) :: Info
      Character(len=200)                   :: string
      ! 
      ! --- Local
      Character(len=4)                     :: Current_Year
      
      call SFL_YearString(Current_Year)
      
      string = " Copyright (C) "// Trim(adjustl(Info%FromYear)) &
                // "-" // Current_Year // " "// &
                trim(adjustl(Info%Author(1))) // " "// trim(adjustl(Info%Email(1)))  // &  
                " and " // trim(adjustl(Info%Author(2))) // " "// trim(adjustl(Info%Email(2)))   

    End Function Copyright_String


  End subroutine Software_Info_Set
  !-------------------------------!



  !--------------------------------------------!
  Subroutine Software_Info_String(Info, string)
  !--------------------------------------------!
    !
    ! Returns a info string about the softaware....
    !  Eg. Name, Version and revision
    !
    Use SFL_Util, Only : SFL_YearString
    Implicit None
    Type(Software_Info_Type), intent(inout) :: Info
    Character(len=*),         intent(out)   :: string
    ! 
    ! --- Local
    Character(len=4)                        :: Current_Year

    call SFL_YearString(Current_Year)

    string = " "//trim(Adjustl(Info%Name))//" ver"//trim(adjustl(Info%Version))//" (rev:"//trim(adjustl(Info%Revision))//")"  
    !&
    !     // "\n\n Copyright (C) 2008-"// Current_Year // " Ingve Simonsen <Ingve.Simonsen@ntnu.no>"
    !     !!// "\n\n Copyright (C) 2008 "// trim(adjustl(Info%Author))//" "// trim(adjustl(Info%Email))

    return

  End Subroutine Software_Info_String
  !----------------------------------!


  !---------------------------------------------------!
  function date_time_string() Result(res)
  !---------------------------------------------------!
    !
    ! Returns a string giving the time and date 
    ! 
    ! 
    !
    Implicit None
    character(len=21) :: res
    ! 
    ! --- Local
    Character(len=4 )    :: date
    Character(len=10)    :: time
    Character(len=5 )    :: zone
    Integer, dimension(8):: values
    character(len=3)     :: month
   

    ! --- get current date and time
    call date_and_time( date, time, zone, values )
    
    ! --- convert to string month
    select case(values(2))
    case(1)
       month ="Jan"
    case(2)
       month ="Feb"
    case(3)
       month ="Mar"
    case(4)
       month ="Apr"
    case(5)
       month ="May"
    case(6)
       month ="Jun"
    case(7)
       month ="Jul"
    case(8)
       month ="Aug"
    case(9)
       month ="Sep"
    case(10)
       month ="Oct"
    case(11)
       month ="Nov"
    case(12)
       month ="Dec"
    case default
       write(*,*) "An internal error occured in the routine  Software_Compile_Date_Time()"
    end select

    Write(res,"(I2.2,' ',a3,' ',I4.4,'  ',I2.2,':',I2.2,':',I2.2)") &
         VALUES(3),month,VALUES(1),   VALUES(5),VALUES(6),VALUES(7)
   
    return

  End function date_time_string
  !----------------------------------------------------!



End Module Software_Info_Mod
!-------------------------------------------------------------------------!





